### ISSUE TITLE
Text 파일 open 오류발생(해결)

### ISSUE THREAD

**Issue by iopopoi** [iopopoi/ERICA_road_shuttle#3]
timecheck코드에서  같은 위치에 있는 time_shuttle을 읽지 못한다.
<br>같은 폴더 안에서가 아닌 해당 폴더 밖에서 text를 찾으려하며 오류가 발생함

**Comment by hihiroo** [comment]
오류수정했습니다. 확인해주세요

**Comment by hihiroo** [comment]
셔틀 시간표 텍스트 파일 open할때 경로를 상대경로로 변경했습니다. 현재 파이썬 파일이 저장되어있는 경로를 받아와서 같은 경로에 있는 텍스트 파일 경로를 찾을 수 있게 됩니다.

**Comment by hihiroo** [comment]
그러므로 텍스트 파일이랑 timecheck파일이랑 같은 폴더에 넣어주세요!

**Comment by iopopoi** [comment]
알겠습니다.
