### ISSUE TITLE
minute2time함수 출력 형식(해결)

### ISSUE THREAD

**Issue by hihiroo** [iopopoi/ERICA_road_shuttle#4]
00:01 분에 경우 minute2time(1)을 호출하면 0:1이 나옵니다.

**Comment by iopopoi** [comment]
수정하겠습니다.

**Comment by hihiroo** [comment]
그리고 25시 00분 같은 경우에는 01시 00분이 나오도록 수정하면 더 좋을거 같습니다!

**Comment by iopopoi** [comment]
25시 00분 같은 경우는 저희 코드에서 나올이유가 없는 시간 입니다.

**Comment by iopopoi** [comment]
함수 확인 후 함수 수정완료 했습니다 .
확인부탁드려요.

**Comment by hihiroo** [comment]
확인했습니다. 현재는 25시 00분 같은 경우가 프로그램 내에서 발생하지 않지만, 나중에 도착 예정시간 계산과정에서 나올 수도 있을 것 같아서 미리 에러를 방지하고자 말씀드렸습니다. 수정된 코드에서는 이 부분이 문제가 되지 않습니다. 수고하셨습니다ㅎㅎ

**Comment by iopopoi** [comment]
오후 11시 이후에  셔틀을 찾는 경우에 관해 생각하지 못해 오류 발생 가능성을
생각하지 못하였습니다.
어떤식으로 작동해야 할지 정확하게 정한 후에 코드를 수정하는게 좋을것 같습니다.
